export const GET_PARTICIPANT = "GET_PARTICIPANT";
export const GET_PARTICIPANTS = "GET_PARTICIPANTS";
export const EDIT_PARTICIPANT = "EDIT_PARTICIPANT";
export const ADD_PARTICIPANT = "ADD_PARTICIPANT";

export const GET_INTERVIEW = "GET_INTERVIEW";
export const GET_INTERVIEWS = "GET_INTERVIEWS";
export const EDIT_INTERVIEW = "EDIT_INTERVIEW";
export const ADD_INTERVIEW = "ADD_INTERVIEW";
